modLoader="javafml"
loaderVersion="[43,)"
license="WTFPL2"
issueTrackerURL="https://gitlab.com/itlfts/im-too-lazy-for-this-shit/issues/"
[[mods]]
modId="springbootstrap"
version="${file.jarVersion}"
displayName="SpringContext - Bootstrap"
logoFile="logo.png"
authors="CKATEPTb"
description='''
By itself, this mod will not give you anything,
this is a library mod, for other mods that
allows use them Spring Context
'''
[[dependencies.springbootstrap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
